// @odh/brand — design tokens (single source of truth for ODH brand).
// Never hardcode these hex values in components — import from here or use the
// Tailwind utilities generated by theme.css (bg-navy, text-gold, ...).

export const colors = {
  navy: "#28254c", // Owl Navy — structure / text
  navyDeep: "#1b1938", // deep navy — gradient end
  gold: "#e9a41b", // Owl Gold — CTA / highlight
  goldSoft: "#fbefd3", // soft gold — tints / badges
  paper: "#fbf8f1", // page background
  ink: "#28254c", // body text
  muted: "#6e6b86", // secondary text
  line: "#eae6db", // borders / dividers
} as const;

export const fonts = {
  display: '"Space Grotesk", ui-sans-serif, system-ui, sans-serif',
  body: '"IBM Plex Sans Thai", ui-sans-serif, system-ui, sans-serif',
} as const;

export const radii = {
  sm: "0.5rem",
  md: "0.75rem",
  lg: "1rem",
  xl: "1.25rem",
  full: "9999px",
} as const;

export const shadow = {
  card: "0 12px 40px -20px rgb(40 37 76 / 0.35)",
  glow: "0 18px 50px -16px rgb(233 164 27 / 0.55)", // gold glow for CTAs
} as const;

export const tokens = { colors, fonts, radii, shadow } as const;

export type Colors = typeof colors;
export type Tokens = typeof tokens;
